[env]
RUST_LOG = "info"
RUST_LIB_BACKTRACE = "1"

[config]
skip_core_tasks = true

[tasks.frontend]
script.pre = "cd frontend"

[tasks.backend]
script.pre = "cd backend"

## BUILD
[tasks.setup-frontend]
extend = "frontend"
script.main = "pnpm install"
condition = { files_not_exist = ["frontend/node_modules"] }

[tasks.build-frontend]
extend = "frontend"
script.main = "pnpm build"
dependencies = ["setup-frontend", "build-backend"]

[tasks.build-backend-bindings]
extend = "backend"
script.main = "cargo test export_bindings"

[tasks.build-backend]
extend = "backend"
script.main = "cargo build"

[tasks.build.run_task]
name = ["build-backend", "build-backend-bindings", "build-frontend"]


## WATCH
[tasks.serve-frontend]
extend = "frontend"
script.main = "cd packages/situ-classroom/dist && basic-http-server"
install_crate = { crate_name = "basic-http-server" }

[tasks.serve-gentle]
script = "cd $GENTLE_ROOT && python3 serve.py"

[tasks.watch-frontend]
extend = "frontend"
script.main = "pnpm watch"
dependencies = ["setup-frontend"]

[tasks.watch-backend]
extend = "backend"
script.main = "cargo watch -d 2 -x 'run --bin situ-server'"
install_crate = { crate_name = "cargo-watch" }

[tasks.watch.run_task]
name = ["serve-frontend", "serve-gentle", "watch-frontend", "watch-backend"]
parallel = true


## CLEAN
[tasks.clean-backend.run_task]
name = ["clean-backend-cargo", "clean-backend-bindings"]

[tasks.clean-backend-cargo]
extend = "backend"
script.main = "cargo clean"

[tasks.clean-backend-bindings]
extend = "backend"
script.main = "rm -rf crates/*/bindings"

[tasks.clean-frontend]
extend = "frontend"
script.main = "pnpm clean"

[tasks.clean.run_task]
name = ["clean-backend", "clean-frontend"]
parallel = true
