[package]
name = "mdbook-situ"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
anyhow = "1"
clap = {version = "3", features = ["derive"]}
mdbook = "0.4"
semver = "1"
pulldown-cmark-to-cmark = "10"
pulldown-cmark = "0.9"
regex = "1"
html-escape = "0.2"
toml = "0.5"